import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppHeader from "@/components/app.header";
import Footer from "@/components/app.footer";
import "./globals.css";
import Content from "@/components/app.content";
import Contact from "@/components/app.contact";
import Projects from "@/components/app.project";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={inter.className}>
      <div className="container mx-auto">
      <AppHeader></AppHeader>
        <Content>
    
        </Content>
        {children}
        <Projects></Projects>
        <Contact></Contact>
        <Footer></Footer>
      </div>
        </body>
      
    </html>
  );
}
